mysql:
  datasource:
    #读库数目
    num: 1
    type-aliases-package: com.it.plus.wcw.entity
    mapper-locations: classpath:/mapper/wcw/*.xml
    config-location: classpath:/mybatis-config.xml
    master:
      url: jdbc:mysql://192.168.85.22:3306/test001?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: slave
      password: slave
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://192.168.85.23:3306/test001?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: master
      password: master
      driver-class-name: com.mysql.jdbc.Driver

rocketmq:
  name-server: 192.168.85.22:9876
  producer:
    group: my-group
    send-message-timeout: 3000
    max-message-size: 4194304
    retry-times-when-send-failed: 2
