mysql:
  datasource:
    #读库数目
    num: 1
    type-aliases-package: com.it.plus.wcw.entity
    mapper-locations: classpath:/mapper/wcw/*.xml
    config-location: classpath:/mybatis-config.xml
    master:
      url: jdbc:mysql://192.168.85.22:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: master
      password: master
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      url: jdbc:mysql://192.168.85.24:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: slave
      password: slave
      driver-class-name: com.mysql.jdbc.Driver

rocketmq:
  name-server: 193.112.185.161:9876
  producer:
    group: my-group
    send-message-timeout: 3000
    max-message-size: 4194304
    retry-times-when-send-failed: 2

server:
  port: 8081

spring:
  application:
    name: zephyr-consumer
  data:
    mongodb:
      host: 192.168.85.22
      port: 27017
      database: test
      username: test
      password: test
  redis:
    host: 192.168.85.22
    port: 6379
    password: root

#dubbo:
#  registry:
#    address: zookeeper://192.168.85.22:2181
#  protocol:
#    name: dubbo
#    port: -1
#  provider:
#    filter: -exception
#  config-center:
#    timeout: 10000

#引入日志配置文件
logging:
  config: classpath:logback-spring.xml
